version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: uni_event_management_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - mysql
        command: sh -c "./wait-for-it.sh mysql:3306 --timeout=60 --strict -- composer install && php artisan migrate --force && php artisan db:seed --force && php-fpm"

    webserver:
        image: nginx:alpine
        container_name: uni_event_management_webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: uni_event_management_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: pass1234
            MYSQL_DATABASE: uni_event_management
            MYSQL_USER: root
            MYSQL_PASSWORD: pass1234
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: uni_event_management_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: pass1234
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - app-network

volumes:
    dbdata:

networks:
    app-network:
        driver: bridge
